name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Unit Tests - Node.js
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install
        run: yarn install

      - name: Compile
        run: yarn build

      - name: Package
        run: yarn run package

      - name: Test
        env:
          INPUT_PRODUCT: "Red Hat Enterprise Linux 9"
          INPUT_COMPONENT: "systemd"
          INPUT_BUGZILLA-INSTANCE: "https://bugzilla.stage.redhat.com"
          INPUT_BUGZILLA-API-TOKEN: ${{ secrets.BUGZILLA_API_TOKEN }}
          INPUT_JIRA-INSTANCE: "https://issues.redhat.com"
          INPUT_JIRA-API-TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: yarn test

      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
